name = "inpriv-burn"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = true

# Static frontend served from ./public (index.html goes here after deploy prep)
[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "BURN_KV"
id = "e0bf863f6dd748aa90f8799ab1bccc42"
